name: Lean verification

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LEAN_NUM_THREADS: 2
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          use-github-cache: true
          use-mathlib-cache: true
          build: true
          test: false
          leanchecker: true
          leanchecker-args: JustinSunPrize
          nanoda: true
          nanoda-allow-sorry: false
          axiom-audit: true
          axiom-audit-root: JustinSunPrize
